### ISSUE TITLE
Pattern length is fixed?

### ISSUE THREAD

**Issue by SyedWasiHaider** [justinj/string-matching-visualization#1]
I tried entering a pattern but I could not enter more than about 10 characters

My example is:

String T = xyxxyxyxyyxyxyxyyxyxyxxy (Text)
String P = xyxyyxyxyxx (Pattern)

Thanks. Your thing has been very very useful.

**Comment by justinj** [comment]
Yeah it is (arbitrarily) limited to 10 characters for the pattern and 30 characters for the text. I didn't want to deal with inputs being too long so these seemed like reasonable limits. I'm happy to bump it up if you think it's worthwhile though.

I'm glad it was helpful!

**Comment by SyedWasiHaider** [comment]
You could just use the length of the  haystack text  as the upper limit.
